/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;
//import busqd.*;
import java.sql.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karen
 */
public class busqda extends javax.swing.JPanel {

    DefaultTableModel tab;
    /**
     * Creates new form busqda
     */
    public busqda() {
        initComponents();
        busqOpc.addItem("Placas");
        busqOpc.addItem("Fecha");
        busqOpc.addItem("Cliente");
        
        //tab.addColumn("Id");
        tab=new DefaultTableModel();
        tab.addColumn("Placas");
        tab.addColumn("Cliente");
        tab.addColumn("Teléfono");
        tab.addColumn("Fecha");
        tab.addColumn("Documento");
        this.table.setModel(tab);
    }
    //String []botones=["Si","No");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraBusq = new javax.swing.JPanel();
        barraBusqText = new javax.swing.JLabel();
        textPlac = new javax.swing.JLabel();
        busqOpc = new javax.swing.JComboBox<>();
        ingresPlac = new javax.swing.JTextField();
        buscar = new javax.swing.JPanel();
        buscarText = new javax.swing.JLabel();
        elim = new javax.swing.JPanel();
        elimIcon = new javax.swing.JLabel();
        modif = new javax.swing.JPanel();
        modIcon = new javax.swing.JLabel();
        division = new javax.swing.JPanel();
        tabla = new javax.swing.JPanel();
        tablee = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(590, 470));

        barraBusq.setBackground(new java.awt.Color(143, 29, 19));

        barraBusqText.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 30)); // NOI18N
        barraBusqText.setForeground(new java.awt.Color(255, 255, 255));
        barraBusqText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraBusqText.setText("B U S Q U E D A ");
        barraBusqText.setToolTipText("");

        javax.swing.GroupLayout barraBusqLayout = new javax.swing.GroupLayout(barraBusq);
        barraBusq.setLayout(barraBusqLayout);
        barraBusqLayout.setHorizontalGroup(
            barraBusqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraBusqText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        barraBusqLayout.setVerticalGroup(
            barraBusqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraBusqLayout.createSequentialGroup()
                .addComponent(barraBusqText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(212, 212, 212))
        );

        textPlac.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        textPlac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textPlac.setText("BUSQUEDA POR:");

        busqOpc.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        busqOpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione una opción" }));
        busqOpc.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        busqOpc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                busqOpcItemStateChanged(evt);
            }
        });
        busqOpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqOpcActionPerformed(evt);
            }
        });

        ingresPlac.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        ingresPlac.setForeground(new java.awt.Color(204, 204, 204));
        ingresPlac.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ingresPlac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresPlacMousePressed(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(166, 166, 166));
        buscar.setForeground(new java.awt.Color(255, 255, 255));

        buscarText.setBackground(new java.awt.Color(166, 166, 166));
        buscarText.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        buscarText.setForeground(new java.awt.Color(255, 255, 255));
        buscarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarText.setText("BUSCAR");
        buscarText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buscarLayout = new javax.swing.GroupLayout(buscar);
        buscar.setLayout(buscarLayout);
        buscarLayout.setHorizontalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarText, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        buscarLayout.setVerticalGroup(
            buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        elim.setBackground(new java.awt.Color(255, 255, 255));

        elimIcon.setBackground(new java.awt.Color(255, 255, 255));
        elimIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elimIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/elim.png"))); // NOI18N
        elimIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elimIconMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elimIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout elimLayout = new javax.swing.GroupLayout(elim);
        elim.setLayout(elimLayout);
        elimLayout.setHorizontalGroup(
            elimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
        elimLayout.setVerticalGroup(
            elimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        modif.setBackground(new java.awt.Color(255, 255, 255));

        modIcon.setBackground(new java.awt.Color(255, 255, 255));
        modIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/modi.png"))); // NOI18N
        modIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout modifLayout = new javax.swing.GroupLayout(modif);
        modif.setLayout(modifLayout);
        modifLayout.setHorizontalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
        modifLayout.setVerticalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        division.setBackground(new java.awt.Color(166, 166, 166));

        javax.swing.GroupLayout divisionLayout = new javax.swing.GroupLayout(division);
        division.setLayout(divisionLayout);
        divisionLayout.setHorizontalGroup(
            divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        divisionLayout.setVerticalGroup(
            divisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setForeground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablee.setViewportView(table);

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla);
        tabla.setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablee, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablee, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(barraBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textPlac, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(busqOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ingresPlac, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(barraBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(busqOpc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPlac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingresPlac))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void busqOpcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_busqOpcItemStateChanged
        String opc = (String) busqOpc.getSelectedItem();
        if(opc.equals("Placas")){
            ingresPlac.setText("Ingrese la placa del coche");
            /*Menu men=new Menu();
            men.setVisible(true);
            dispose();*/
        }if(opc.equals("Fecha")){
            ingresPlac.setText("Ingrese la fecha");

        }if(opc.equals("Cliente")){
            ingresPlac.setText("Ingrese el nombre del cliente");
        }
    }//GEN-LAST:event_busqOpcItemStateChanged

    private void ingresPlacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresPlacMousePressed
       if (ingresPlac.getText().equals("Ingrese la placa del coche")){
            ingresPlac.setText("");
            ingresPlac.setForeground(Color.black);
        }
       if (ingresPlac.getText().equals("Ingrese la fecha")){
            ingresPlac.setText("");
            ingresPlac.setForeground(Color.black);
        }
       if (ingresPlac.getText().equals("Ingrese el nombre del cliente")){
            ingresPlac.setText("");
            ingresPlac.setForeground(Color.black);
        }
    }//GEN-LAST:event_ingresPlacMousePressed

    private void buscarTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTextMouseEntered
        buscarText.setBackground(new Color(240,240,240));
        buscar.setBackground(new Color(240,240,240));
        buscarText.setForeground(Color.black);
    }//GEN-LAST:event_buscarTextMouseEntered

    private void buscarTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTextMouseExited
        buscarText.setBackground(new Color(166,166,166));
        buscar.setBackground(new Color(166,166,166));
        buscarText.setForeground(Color.white);
    }//GEN-LAST:event_buscarTextMouseExited

    private void modIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modIconMouseEntered

    private void elimIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimIconMouseEntered
        //JOptionPane.showConfirmDialog(this, "¿Desea eliminar campo?");
    }//GEN-LAST:event_elimIconMouseEntered

    private void elimIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimIconMousePressed
        //JOptionPane.showConfirmDialog(this, "¿Desea eliminar campo?");
        JOptionPane.showConfirmDialog(null, "¿Desea eliminar el campo?",
                "OK_CANCEL_OPTION", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_elimIconMousePressed

    private void buscarTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarTextMouseClicked
//        try {
//            //1.
//            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost/autofast_clientes?autoReconnect=true&useSSL=false", "root", "1821");
//            //2.
//            Statement myStmt = myConn.createStatement();
//            //3.
//            ResultSet myRs = myStmt.executeQuery("select * from estudiante301 where numero_cuenta = " + num_buscar);
//
//            //4.
//            while (myRs.next()) {
//                System.out.println(myRs.getInt(1) + " " + myRs.getString(2) + " " + myRs.getString(3) + " " + myRs.getString(4));
//                cal1 = myRs.getDouble("parcial1");
//                cal2 = myRs.getDouble("parcial2");
//                cal3 = myRs.getDouble("parcial3");
//
//                //imprime calificaciones
//                System.out.println("Su calificación parcial 1 es: " + cal1);
//                System.out.println("Su calificación parcial 2 es: " + cal2);
//                System.out.println("Su calificación parcial 3 es: " + cal3);
//                promedio = (cal1 + cal2 + cal3) / 3;
//                System.out.println("Su promedio es: " + promedio);
//                System.out.println("");
//
//            }
//            //System.out.println(myRs.getString("x") + ", " + myRs.getString("y"))
//        } catch (SQLException e) {
//            e.getStackTrace();
//        }
    }//GEN-LAST:event_buscarTextMouseClicked

    private void busqOpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqOpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busqOpcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraBusq;
    private javax.swing.JLabel barraBusqText;
    private javax.swing.JPanel buscar;
    private javax.swing.JLabel buscarText;
    private javax.swing.JComboBox<String> busqOpc;
    private javax.swing.JPanel division;
    private javax.swing.JPanel elim;
    private javax.swing.JLabel elimIcon;
    private javax.swing.JTextField ingresPlac;
    private javax.swing.JLabel modIcon;
    private javax.swing.JPanel modif;
    private javax.swing.JPanel tabla;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablee;
    private javax.swing.JLabel textPlac;
    // End of variables declaration//GEN-END:variables
}
