/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;
import java.awt.Color;

/**
 *
 * @author karen
 */
public class Help extends javax.swing.JPanel {

    int xMause, yMause;
    
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraIni = new javax.swing.JPanel();
        barraIniText = new javax.swing.JLabel();
        INIC_SES = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        barraIni.setBackground(new java.awt.Color(143, 29, 19));

        barraIniText.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 30)); // NOI18N
        barraIniText.setForeground(new java.awt.Color(255, 255, 255));
        barraIniText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraIniText.setText("A Y U D A ");
        barraIniText.setToolTipText("");

        javax.swing.GroupLayout barraIniLayout = new javax.swing.GroupLayout(barraIni);
        barraIni.setLayout(barraIniLayout);
        barraIniLayout.setHorizontalGroup(
            barraIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraIniLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(barraIniText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraIniLayout.setVerticalGroup(
            barraIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraIniText)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        INIC_SES.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        INIC_SES.setText("MANUAL DE USUARIO");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/maUs.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(INIC_SES, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(INIC_SES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel INIC_SES;
    private javax.swing.JPanel barraIni;
    private javax.swing.JLabel barraIniText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
