/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu;
import ini.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class inic extends javax.swing.JPanel {

    /**
     * Creates new form busqda
     */
    public inic() {
        initComponents();
    }
    //String []botones=["Si","No");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraIni = new javax.swing.JPanel();
        barraIniText = new javax.swing.JLabel();
        mensaj1 = new javax.swing.JLabel();
        mensaj2 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(590, 470));

        barraIni.setBackground(new java.awt.Color(143, 29, 19));

        barraIniText.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 30)); // NOI18N
        barraIniText.setForeground(new java.awt.Color(255, 255, 255));
        barraIniText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraIniText.setText("I N I C I O");
        barraIniText.setToolTipText("");

        mensaj1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mensaj1.setForeground(new java.awt.Color(255, 255, 255));
        mensaj1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensaj1.setText("Administración/Control/Automotriz");

        mensaj2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mensaj2.setForeground(new java.awt.Color(255, 255, 255));
        mensaj2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensaj2.setText("Presupuesto Mecánico");

        javax.swing.GroupLayout barraIniLayout = new javax.swing.GroupLayout(barraIni);
        barraIni.setLayout(barraIniLayout);
        barraIniLayout.setHorizontalGroup(
            barraIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraIniLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(barraIniText, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraIniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(mensaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraIniLayout.setVerticalGroup(
            barraIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraIniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(barraIniText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barraIniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ini/auto.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(barraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(icon)
                .addGap(0, 77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraIni;
    private javax.swing.JLabel barraIniText;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel mensaj1;
    private javax.swing.JLabel mensaj2;
    // End of variables declaration//GEN-END:variables
}
