/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package submenus;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import java.awt.Color;

/**
 *
 * @author karen
 * 
 */
public class menuItem extends javax.swing.JPanel {
    
    public void setShowing(boolean showing) {
        this.showing = showing;
    }

    public ArrayList<menuItem> getSubMenu() {
        return subMenu;
    }

    /**
     * Creates new form menuItem
     */
    private final ArrayList<menuItem> subMenu = new ArrayList<>();
    private ActionListener act;

    public menuItem(Icon icon, String menuName, ActionListener act, menuItem... subMenu) {
        initComponents();
        lbIcon.setIcon(icon);
        tabaReaText.setText(menuName);
        if (act != null) {
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 45));
        for (int i = 0; i < subMenu.length; i++) {
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }
    public menuItem() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabaReaText = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(155, 43, 32));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(120, 45));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        tabaReaText.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 14)); // NOI18N
        tabaReaText.setForeground(new java.awt.Color(255, 255, 255));
        tabaReaText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabaReaText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabaReaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabaReaTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tabaReaTextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabaReaTextMousePressed(evt);
            }
        });

        lbIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabaReaText, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabaReaText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < subMenu.size(); i++) {
                    sleep();
                    subMenu.get(i).setVisible(true);
                }
                showing = true;
                getParent().repaint();
                getParent().revalidate();
            }
        }).start();
    }
    private void hideMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = subMenu.size() - 1; i >= 0; i--) {
                    sleep();
                    subMenu.get(i).setVisible(false);
                    subMenu.get(i).hideMenu();
                }
                getParent().repaint();
                getParent().revalidate();
                showing = false;
            }
        }).start();
    }

    private void sleep() {
        try {
            Thread.sleep(20);
        } catch (Exception e) {
        }
    }
    
    private void tabaReaTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabaReaTextMouseEntered
        lbIcon.setBackground(new Color(175,62,54));
        tabaReaText.setBackground(new Color(175,62,54));
    }//GEN-LAST:event_tabaReaTextMouseEntered

    private void tabaReaTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabaReaTextMouseExited
        lbIcon.setBackground(new Color(155,43,32));
        tabaReaText.setBackground(new Color(155,43,32));
    }//GEN-LAST:event_tabaReaTextMouseExited
    
    private boolean showing = false;
    private void tabaReaTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabaReaTextMousePressed
        if (showing) {
            hideMenu();
        } else {
            showMenu();
        }
        if (act != null) {
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_tabaReaTextMousePressed

    private void lbIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMouseEntered
        lbIcon.setBackground(new Color(175,62,54));
        tabaReaText.setBackground(new Color(175,62,54));
    }//GEN-LAST:event_lbIconMouseEntered

    private void lbIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMouseExited
        lbIcon.setBackground(new Color(155,43,32));
        tabaReaText.setBackground(new Color(155,43,32));
    }//GEN-LAST:event_lbIconMouseExited

    private void lbIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbIconMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        lbIcon.setBackground(new Color(175,62,54));
        tabaReaText.setBackground(new Color(175,62,54));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        lbIcon.setBackground(new Color(155,43,32));
        tabaReaText.setBackground(new Color(155,43,32));
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel tabaReaText;
    // End of variables declaration//GEN-END:variables
}
